### PR TITLE
create network for user 0

### PR DESCRIPTION
**Pull request by albjeremias**

### CODE REVIEW

**Comment by albjeremias** [comment]
hay que definir esto en la red por defeto:
```
 network = new Network(
        {
          "name": "Perritos en adopcion",
          "place": "Livorno, Italia",
          "tags": ["livorno", "queso"],
          "url": "net/url",
          "avatar": "image/url.png",
          "description": "Net for animal rescue",
          "privacy": "publico",
          "geoPlace": {
            "coordinates": [
              -9.16534423828125,
              38.755154214849426
            ], "type": "Point"
          },
          "radius": 240,
          "friendNetworks": [1, 2],
          "owner": savedUser.id,
        }
```

**Comment by watchoutfreedom** [comment]
ok copy

**Comment by albjeremias** [comment]
I'd rather that the frontend would just ask the user to create the network 0, if the backend returns no networks... because i dont think that this solution is very strong.

**Comment by watchoutfreedom** [comment]
yes probably it's better the first time , when there are no nets, ask to register, and the to create one.

**Pull request merged**
