### PR TITLE
add geojson to button model, fix tests and db

### PR DESCRIPTION
**Pull request by albjeremias**

### CODE REVIEW

**Comment by albjeremias** [comment]
missing the networks... next

**Comment by albjeremias** [comment]
It's ready! @watchoutfreedom 
next i will work on issue #23

**Comment by watchoutfreedom** [comment]
Cool I'll check

**Comment by watchoutfreedom** [comment]
Now checking the data init I see there's no date, also the description seems mandatory but I suppose it's just your example ? Sorry for not getting the example

**Comment by albjeremias** [comment]
> Now checking the data init I see there's no date, also the description seems mandatory but I suppose it's just your example ? Sorry for not getting the example

I don't understand. can u show me an example?

**Comment by albjeremias** [comment]
@watchoutfreedom ^

**Comment by albjeremias** [comment]
maybe this might help
https://github.com/helpbuttons/hb-back/pull/28#issuecomment-919374653

**Pull request merged**
